name: rocky

services:
  backend:
    build:
      context: .
      dockerfile: rocky-backend/Dockerfile
    networks:
      - rocky-network


  frontend:
    build:
      context: .
      dockerfile: rocky-interface/Dockerfile
    ports:
      - "3000:4173"
    networks:
      - rocky-network
  

networks:
  rocky-network:
    driver: bridge